apiVersion: apps/v1
kind: Deployment
metadata:
 name: birthday-telebot
spec:
 replicas: 1
 selector:
   matchLabels:
     app: birthday-telebot
 template:
   metadata:
     labels:
       app: birthday-telebot
   spec:
     containers:
     - name: birthday-telebot
       image: ghcr.io/ilyademidow/birthday_telebot:latest
       imagePullPolicy: Always
       volumeMounts:
       - name: config-js
         mountPath: /tmp/telebot/lib
     imagePullSecrets:
      - name: github-cr
     volumes:
       - name: config-js
         configMap:
           name: config-js
