apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-telebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birthday-telebot
  template:
    metadata:
      labels:
        app: birthday-telebot
    spec:
      volumes:
        - name: pers-stor
          hostPath:
            path: /tmp/kubevolume
      containers:
      - name: birthday-telebot
        image: ghcr.io/ilyademidow/birthday_telebot:latest
        imagePullPolicy: Always
        env:
        - name: TELEBOT_AUTH_ID
          value: "{{ .Values.telebot_auth_id }}"
        - name: TELEBOT_CHANNEL_ID
          value: "{{ .Values.telebot_channel_id }}"
        - name: TELEBOT_NAME
          value: "{{ .Values.telebot_name }}"
        volumeMounts:
          - name: pers-stor
            mountPath: /tmp/telebot/db
      imagePullSecrets:
        - name: github-cr
